version: '3'
services:
  mysql:
    image: mysql:5.7  # Use a specific MySQL version for stability
    container_name: my-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bearsjava
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  spring-boot-app:
    build:
      context: . # Use a dot (.) to specify the current directory as the build context
      dockerfile: Dockerfile  # If you have a custom Dockerfile
    container_name: my-spring-boot-app
    ports:
      - "8082:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bearsjava
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin